name: 'Setup'
description: 'Setup Node, Rust, and Tauri'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    # # # # # # # # # #
    # Linux Packages  #
    # # # # # # # # # #

    - name: install dependencies (ubuntu only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    # # # # #
    # NODE  #
    # # # # #

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: set npm version
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        set -e
        grep '"version": "0.0.0",' 'package.json'
        echo "${GITHUB_REF_NAME:1}"
        sed_expr='s/"0.0.0"/"'"${GITHUB_REF_NAME:1}"'"/'
        echo "$sed_expr"
        sed -i -e "$sed_expr" 'package.json'

    # # # # #
    # RUST  #
    # # # # #

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
