name: 'Setup'
description: 'Setup Node, Rust, and Tauri'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    # # # # #
    # NODE  #
    # # # # #

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18
        cache: 'yarn'

    - name: Yarn install
      shell: bash
      run: yarn && yarn build

    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - name: set npm version
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        set -e
        grep '"version": "0.0.0",' 'package.json'
        echo "${GITHUB_REF_NAME:1}"
        sed_expr='s/"0.0.0"/"'"${GITHUB_REF_NAME:1}"'"/'
        echo "$sed_expr"
        sed -i -e "$sed_expr" 'package.json'

    # # # # #
    # RUST  #
    # # # # #

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Cargo build
      run: cargo build --release
      working-directory: src-tauri
      shell: bash
