name: 'Setup'
description: 'Setup Node, Rust, and Tauri'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18
        cache: 'yarn'
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: set npm version
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: npm version ${{ env.GITHUB_REF_NAME }}
