name: 'Setup'
description: 'Setup Node, Rust, and Tauri'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    # # # # # # # # # #
    # Linux Packages  #
    # # # # # # # # # #

    - name: install dependencies (ubuntu only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    # # # # #
    # NODE  #
    # # # # #

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: set npm version
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      env:
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        set -e
        grep '"version": "0.0.0",' 'package.json'
        echo "${GITHUB_REF_NAME:1}"
        sed_expr='s/"0.0.0"/"'"${GITHUB_REF_NAME:1}"'"/'
        echo "$sed_expr"
        sed -i -e "$sed_expr" 'package.json'

    - name: Get npm cache directory
      id: npm-cache
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - uses: actions/cache@v3
      id: npm-cache
      # use this to check for `cache-hit` ==>
      if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # # # # #
    # RUST  #
    # # # # #

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
